version: "3.9"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      # MSSQL_PID=Developer|Express|Standard|Enterprise|EnterpriseCore
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=Pass@1234
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=Pass@1234
      - MYSQL_DATABASE=mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=Pass@1234
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  mariadb-data:
  mssql-data: